apm-server:
  host: 0.0.0.0:8200
  kibana:
    enabled: true
    host: kb-container:5601
    protocol: http
  rum:
    enabled: true
    limit:
      event_rate: 10000
    source_mapping:
      enabled: true
  secret_token: 9426C166-8395-4A5E-81AF-C5A19AD3BF4F

output.elasticsearch:
  hosts: ["http://es-container:9200"]
  protocol: http
  ssl.verification_mode: none